- name: 'play1- Installdocker'
  hosts: dockermanager
  become: yes
  tasks:
    - name: Install Python 3.6
      yum:
        name: python36
        state: present
      register: out1
      tags:
        - python-install
    - debug:
        var: out1
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present	
    - name: Copy the war file, dockerfile & training-com.yml to docker master server
      copy:
        src: /etc/ansible/webapp/
        dest: /tmp/webapp/
        owner: ansible
        group: root
        mode: '0777'
      tags:
        - copy_code

- name: 'play2- Running container'
  hosts: dockermanager
  gather_facts: no
  become: yes
  tasks:
    - name: "Build an image "
      docker_image:
        build:
          path: /tmp/webapp
        source: build
        name: tomcat
        tag: latest
      register: out5
      tags: docker-image-build
    - debug:
        var: out5

    - name: Restart a container
      docker_container:
        name: tomcat
        image: tomcat
        state: started
        restart: yes
        ports:
          - "8080:8080"

