- name: 'play1- Installdocker'
  hosts: dockermanager
  become: yes
  tasks:
    - name: Install Python 3.6
      yum:
        name: python36
        state: present
      register: out1
      tags:
        - python-install
    - debug:
        var: out1
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present	
- name: 'play2- Running container'
  hosts: dockermanager
  become: yes
  tasks:
    - name: "Build an image and push it to a private repo"
      docker_image:
        build:
          path: /etc/ansible/webapp
        name: tomcat
        tag: latest
      register: out5
      tags: docker-image-build
    - debug:
        var: out5

    - name: Restart a container
      docker_container:
        name: tomcat
        image: tomcat
        tag: latest
        state: started
        restart: yes
        ports:
          - "8080:8080"
