- name: 'play1- Installdocker'
  hosts: dockermanager
  gather_facts: no
  become: yes
  tasks:
    - name: Install Python 3.6
      yum:
        name: python36
        state: present
      register: out1
      tags:
        - python-install
    - debug:
        var: out1
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
      register: out2
    - debug:
        var: out2
      tags:
        - Install docker dependencies
    - name: Copy the war file, dockerfile
      copy:
        src: /etc/ansible/webapp/
        dest: /tmp/webapp/
        owner: ansible
        group: root
        mode: '0777'
      tags:
        - copy_code

- name: 'play2- Deployment to containers'
  hosts: dockermanager
  gather_facts: no
  become: yes
  tasks:
    - name : "Remove existing container"
      docker_container:
        state: absent
        name: tomcat
        force: yes
      register: out4
    - debug:
        var: out4
      tags:
        - remove existing container

    - name : "Remove existing docker image"
      docker_image:
        state: absent
        name: tomcat
        tag: latest
        force: yes
      register: out3
    - debug:
        var: out3
      tags:
        - remove existing docker image
    - name: "Build an image "
      docker_image:
        build:
          path: /tmp/webapp
        source: build
        name: tomcat
        tag: latest
      register: out5
      tags: docker-image-build
    - debug:
        var: out5
      tags:
        - Build image

    - name: Restart a container
      docker_container:
        name: tomcat
        image: tomcat
        state: started
        restart: yes
        ports:
          - "8080:8080"
        tags:
          - starting the container

