- name: 'play1- Installdocker'
  hosts: dockermanager
  become: yes
  tasks:
    - name: Install Python 3.6
      yum:
        name: python36
        state: present
      register: out1
      tags:
        - python-install
    - debug:
        var: out1

    - name: 'Install python-pip'
	  yum:
	    name: python-pip
		state: present
		
	- name: Install docker-py python module
	  pip:
	    name: docker-py
		state: present
		
    - name: Install docker
	  yum:
	    name: docker
		state: present
	
- name: 'play2- Running container'
  hosts: dockermanager
  become: yes
  tasks:
    - name: Restart a container
      docker_container:
        name: webapp
        image: mani2595/webapp
    state: started
    restart: yes
    ports:
     - "8080:8080"
